### ISSUE TITLE
Public plugin PHP Version

### ISSUE THREAD

**Issue by pyronaur** [Automattic/gutenberg-ramp#16]
I noticed shorthand arrays ( PHP 5.4 feature ) in the plugin. Which PHP versions are we aiming for the public release?

If we want the plugin to be useful for absolutely every WordPress installation then we still need to go for PHP 5.2.4.

I usually wouldn't suggest using an old PHP version, but since this is a plugin intended to improve Gutenberg compatibility for all sites - we might have to go for core-compatibility.

**Comment by GaryJones** [comment]
For future reference, the current PHP requirement for this plugin is [stated](https://github.com/Automattic/gutenberg-ramp/blob/d7d353aafda9c89f9669add9828800b87621d760/readme.txt#L6) in the readme as PHP `5.5`.
