### ISSUE TITLE
In settings, improve checkbox UI for enabling custom post types

### ISSUE THREAD

**Issue by klasharr** [Automattic/gutenberg-ramp#56]
I have enabled Gutenberg Ramp but don't see checkboxes for all the custom post types on the site:

![image](https://user-images.githubusercontent.com/5604969/41402292-d1ea42b6-6fb9-11e8-8459-db157a809921.png)

As a user, it isn't immediately clear to me why the checkboxes are missing and it looks like Ramp doesn't fully work. Looking for an explanation leads me to: [https://wordpress.org/plugins/gutenberg-ramp/#screenshots](https://wordpress.org/plugins/gutenberg-ramp/#screenshots) where we have:

>Some post types are not showing up on the settings screen
>Post types that are not compatible with Gutenberg will not show up. If you think you have found a false negative (posts in that post type DO work with Gutenberg, when Ramp plugin is deactivated) please report it as an issue on GitHub here.

If custom post types are incompatible with Gutenberg, it would be a better user experience to say which don't work with a link to more information, perhaps including them in the list but with checkboxes greyed out and inactive.

**Comment by lukecav** [comment]
Any custom post types created by using [Pods](https://github.com/pods-framework/pods), do not show up in the Gutenberg Ramp settings.

**Comment by maevelander** [comment]
Thanks for raising this @klasharr 

A quick and easy fix would be to add some explanatory text:
>  Post types that are not compatible with Gutenberg do not appear here. [Learn more.](https://wordpress.org/plugins/gutenberg-ramp/#faq)

A more advanced solution would be to actually check for post types that are incompatible and display a list of them. I'd propose a simple text based list, something like this:
> The following post types were found but are **not** compatible with Gutenberg: **[list of post types]** [Learn more.](https://wordpress.org/plugins/gutenberg-ramp/#faq)

@klsharr and @rogertheriault  both suggested displaying the incompatible post types as greyed out... my concern with that is that we're already using that style to indicate a post type which IS compatible but which is controlled by the function `gutenberg_ramp_load_gutenberg()` in code (overriding the UI).

@justnorris  Thoughts?

**Comment by maevelander** [comment]
> Any custom post types created by using Pods, do not show up in the Gutenberg Ramp settings.

@lukecav Are you reporting that as a false negative? ie post types created by Pods ARE compatible but not showing?

**Comment by justnorris** [comment]
@lukecav I installed Pods and created a custom post type called "Super Post" and Ramp does show that post type to me if the REST option is enabled in Pods as well.

To test this out further, I disabled Ramp completely and activated Gutenberg. If a post type in Pods doesn't have REST enabled - it doesn't support Gutenberg and falls back to TinyMCE (at least for now in WordPress 4.9.6) - so I don't think the issue you saw is Ramp related. If it is - please create a new issue with steps to reproduce so that I can debug it.

@maevelander I'm working on listing out the unsupported post types to avoid confusion.

**Comment by lukecav** [comment]
@justnorris 

My mistake, custom post types created by Pods, do show in in the Gutenberg Ramp settings when the [REST API](https://pods.io/docs/build/extending-core-wordpress-rest-api-routes-with-pods/) is indeed enabled for that Pods.

**Comment by maevelander** [comment]
@justnorris  How about this?

![gutenberg-ramp-ui](https://user-images.githubusercontent.com/4695433/41641904-596a4b58-7499-11e8-8756-80739830a04f.jpg)

Moved the sentence about the function up so we don't have little bits and pieces floating everywhere. 

Used admin notice style to draw attention
