### ISSUE TITLE
Cross linking an issue in regards to additional editing options 

### ISSUE THREAD

**Issue by paaljoachim** [Automattic/gutenberg-ramp#57]
Hey

I just want to cross link this issue as a possibility...
Making it easier to transition to Gutenberg
https://github.com/WordPress/gutenberg/issues/7060

Using Gutenberg on some specific post types it would be good to have the opportunity on the frontend when clicking edit to have it open in either Gutenberg or the classic editor.

**Comment by maevelander** [comment]
Hi @paaljoachim - thanks for your suggestion.

> it would be good to have the opportunity on the frontend when clicking edit to have it open in either Gutenberg or the classic editor.

This is possible using the [Classic Editor](https://wordpress.org/plugins/classic-editor/) plugin. Screenshots:
![classic-editor-1](https://user-images.githubusercontent.com/4695433/41517634-095bbb52-72ef-11e8-8831-b47357873e51.png)
![classic-editor-2](https://user-images.githubusercontent.com/4695433/41517635-0994fd86-72ef-11e8-96ad-fa239d2c2a02.png)

With this in mind, I do not see a great need to replicate this functionality in Ramp.

In fact, Ramp plugin was designed for a slightly different use-case - to fit the needs of complex, often highly customised authoring workflows like those we see on large enterprise sites at WordPress.com VIP. In these cases we explicitly do not want authors able to choose which editor to use (Gutenberg or Classic). Rather, that decision is set by the theme developers at a higher level, and locked on a post type or post_id basis.

So for both these reasons I don't think this is something we'd incorporate into Ramp.
