### ISSUE TITLE
Suggested enhancements - to plugin or to documentation

### ISSUE THREAD

**Issue by dartiss** [Automattic/gutenberg-ramp#58]
A user on the wp.org forum has suggested some improvements - either to the plugin itself or to clarify better within the README.

> As a non-developer (ie a user with little programming knowledge) I would welcome some more help in the FAQs with how to do the following (or an enhancement to the plugin to enable the following).
> 
> Instead of listing every single post ID that I want to apply Gutenberg to, I would like to be able to apply it to:
> 
> * a numerical range of IDs; and/or
> * all IDs greater than or less than a particular number;
> * a particular post category; and/or
> * all posts except an ID (or a range of IDs etc).
> 
> One particular option I would like to achieve, as a starting point, is to apply Gutenberg to new posts/pages (ie those with an ID number greater than [X]) but have all existing pages and posts remain in the classic editor, until I have been able to go through and check out what editing, if any, is needed when they are in Gutenberg.

https://wordpress.org/support/topic/excellent-but-would-welcome-some-extra-help-for-non-developers/

I'll keep the wp.org forum updated with any comments made here.

**Comment by peteschiebel** [comment]
I had this same thought/request, that it could be useful if you could set a starting point for when Gutenberg is the default editor, my first thought was 'all IDs greater than a particular number'. The other suggestions seem interesting as well, particularly the 'all posts except an ID (or range of IDs etc).

**Comment by mattoperry** [comment]
Noting that I've opened https://github.com/Automattic/gutenberg-ramp/issues/60 to attempt to handle this suggestion and other similar ones in a general way.

**Comment by mattoperry** [comment]
(we can keep this open, but we'll probably focus work on that other issue.)

**Comment by maevelander** [comment]
Closing this issue in favour of #60
