### ISSUE TITLE
Disable 'try Gutenberg' banner in wp 4.9.8, if using Ramp

### ISSUE THREAD

**Issue by dartiss** [Automattic/gutenberg-ramp#61]
Suggested by a user on the wp.org support forum.

> Do you have plans to have a setting that will disable the “Try Gutenberg” callout that’s slated for WP 4.9.8?
> 
> It would seem to make sense to disable the callout by default, since Gutenberg is disabled by default with this plugin. And I LOVE that your default setting is disabling Gutenberg sitewide.

User goes into more details about this, but is basically not installing Gutenberg so the current checks with the banner code will cause it to appear ([it checks if Gutenberg is already installed](https://core.trac.wordpress.org/attachment/ticket/41316/41316.12.diff), which is not an automatic assumption for Ramp users).

I've left the support ticket open, so please update the user if there is any progress with this - https://wordpress.org/support/topic/feature-request-disable-try-gutenberg-callout/

**Comment by dartiss** [comment]
The following code should remove the banner...

`remove_action( 'try_gutenberg_panel', 'wp_try_gutenberg_panel' );`

**Comment by pbiron** [comment]
I just released a [little plugin](https://github.com/pbiron/hide-try-gutenberg-callout) that gives site admins/agencies/hosting companies/etc more fine-grained control over who sees the `Try Gutenberg callout` (more fine-grained that the "shotgun approach" as in [the comment](#issuecomment-404069729) above).

In particular, it lets site admins:

- hide the callout for all users (i.e., the "shotgun approach")
- hide the callout for all users that do not have `edit_posts` capability (see trac [41316#comment:182](https://core.trac.wordpress.org/ticket/41316#comment:182))
- hide the callouot for specific users that do have `edit_posts` (i.e., only allow specific "trusted" users to see the callout)
- disable Gutenberg for all users for whom the callout is hidden by the above settings

As it says in the README:

> To prove to myself that showing/hiding the callout need not be an all or nothing proposition, I quickly threw together this little plugin.

I'd be happy to work with you to integrate these use-cases into Ramp...once we get 4.9.8 out the door, of course.

**Comment by justnorris** [comment]
The direction that Gutenberg Ramp is aiming at is to eventually allow Gutenberg to be enabled for everyone, so I'm not entirely convinced it's the place for Ramp to disable any notifications at all.

The purpose of Ramp is to allow people to gradually start using Gutenberg. I don't think that removing notifications is going to facilitate that.

I do understand that people might have different workflows and intentions for how the admin UI is supposed to look like for their site. I'm happy that @pbiron made a plugin to control exactly that for people who don't want to write their own conditional to remove the notification through the filter.

We should probably test if the labels make sense though when Gutenberg is enabled through Ramp. Maybe even customize the message to reflect the enabled Ramp settings? For example, what should the message look like if Gutenberg is enabled through Ramp on Posts and Pages but no other post type? cc @maevelander

**Comment by pbiron** [comment]
> The direction that Gutenberg Ramp is aiming at is to eventually allow Gutenberg to be enabled for everyone, so I'm not entirely convinced it's the place for Ramp to disable any notifications at all.

Completely understand.  The reason I commented on this ticket is that @pento suggested I do so.

**Comment by justnorris** [comment]
Thanks for that! I wasn't aware of that discussion going on about the callout. My response wasn't aimed directly at your comment but as a long coming response to the issue as a whole :)

By the way - have you considered submitting the plugin to .org? I think there is still a little time left until the 4.9.8 release?

**Comment by pbiron** [comment]
I've thought about it but as of this moment I'm not planning on it.  One reason for that is that it doesn't have any specific support for multisite, which I think it should have before putting in the repo:

- let admins specify default behavior network-wide
- and override that default behavior on a site-by-site basis

**Comment by justnorris** [comment]
4.9.8 has been out for a while now and we still haven't removed the notification by default, so I think we can leave it as is and close the issue :)

Thanks everyone for participating.
