### ISSUE TITLE
allow opt-in to Gutenberg by post/page slug or tag

### ISSUE THREAD

**Issue by haszari** [Automattic/gutenberg-ramp#66]
Currently this plugin allows opt-in to Gutenberg on a post-type or id basis.

In many sites, post-type is not practical, for example if the site contains a lot of content. 

Opt-in by ID is specific enough to allow such sites to gradually transition to Gutenberg, one post at a time. However, IDs are tied to a specific database instance, which makes this approach hard to manage across live/production and development environments.

If this plugin allowed opt-in by post slug, or by a tag, this would allow large complex sites to easily manage which posts use Gutenberg, and to do this consistently across developer environments and production.

**Comment by maevelander** [comment]
Thanks for the suggestion @haszari   Issue #60 seeks to address this by allowing `gutenberg_ramp_load_gutenberg` to accept any `WP_Query` argument. This would be very flexible - the available parameters would be basically all of these:  https://codex.wordpress.org/Class_Reference/WP_Query#Parameters

I'll close this issue now in favour of #60 and discussion can continue over there.  Thanks again.

**Comment by haszari** [comment]
Thanks @maevelander – do you know have an idea of when we might get an update including a fix for #60?
