### ISSUE TITLE
wpcom_vip_load_gutenberg doesn't allow meta boxes to be loaded

### ISSUE THREAD

**Issue by andrewfleming** [Automattic/gutenberg-ramp#69]
Originally reported by @micahwave 

The priority of the `plugins_loaded` hooks is currently set in a way that makes it so no custom meta boxes get loaded.

If you use wpcom_vip_load_gutenberg, it's going to enable gutenberg here:

https://github.com/Automattic/gutenberg-ramp/blob/8017c04609a9589b380b09fb66da5ea81acf4f8a/inc/class-gutenberg-ramp.php#L40

The issue is that gutenberg itself registers a `plugins_loaded` hook at a lower priority:

https://github.com/WordPress/gutenberg/blob/master/lib/register.php#L27

With the current setup, the `gutenberg_trick_plugins_into_registering_meta_boxes` function is never called because ramp isn't activated in time.

If you change the `load_decision` hook priority to 5 it seems to fix the issue.

**Comment by micahwave** [comment]
Here's a PR that fixes this issue: https://github.com/Automattic/gutenberg-ramp/pull/68

**Comment by maevelander** [comment]
This issue is resolved by #70 - the plugins_loaded hook priority no longer exists in 1.1
