### ISSUE TITLE
Disable Ramp when Gutenberg version requirements aren't met

### ISSUE THREAD

**Issue by justnorris** [Automattic/gutenberg-ramp#71]
Gutenberg Ramp 1.1 requires Gutenberg 3.5 or higher to work properly.

We should deactivate Gutenberg Ramp if the version requirements aren't met and display a notice informing the user that Gutenberg should be updated to 3.5+ for Ramp to work.

**Comment by maevelander** [comment]
Proposed admin notice text:

> Plugin deactivated. Ramp requires Gutenberg plugin v3.5 or higher. Please update Gutenberg then reactivate Ramp.

**Comment by justnorris** [comment]
Maybe

> Plugin deactivated. Ramp requires Gutenberg plugin v3.5 or higher. Please update and activate Gutenberg then reactivate Ramp.

Ramp will auto-load Gutenberg if necessary, but I think at this point it'd be better for WordPress to handle the plugin activation.

**Comment by justnorris** [comment]
Fixed by #75
